services:
  audiobookshelf:
    image: advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - 13378:80
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/chiefbash/docker/audiobookshelf/config:/config
      - /home/chiefbash/docker/audiobookshelf/metadata:/metadata
      - /mnt/HDD1/books/audiobooks:/audiobooks
      - /mnt/HDD1/books/manga:/manga
      - /mnt/HDD1/books/novels:/novels
      - /mnt/HDD1/podcasts:/podcasts
    restart: unless-stopped

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/chiefbash/docker/syncthing/config:/config
      - /home/chiefbash:/data1
      - /mnt:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

  filezilla:
    image: jlesage/filezilla:latest
    container_name: filezilla
    ports:
      - 5050:5050
    volumes:
      - /home/chiefbash/docker/filezilla/config:/config:rw
      - /mnt:/storage:rw
    restart: unless-stopped

  speedtest:
    image: openspeedtest/latest
    container_name: speedtest
    ports:
      - 3020:3000
      - 3021:3001
    restart: unless-stopped