services:
    audiobookshelf:
      image: advplyr/audiobookshelf:latest
      container_name: audiobookshelf
      ports:
        - 13378:80
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Chicago
      volumes:
        - /home/chiefbash/docker/audiobookshelf/config:/config
        - /home/chiefbash/docker/audiobookshelf/metadata:/metadata
        - /mnt/HDD15/books/audiobooks:/audiobooks
      restart: unless-stopped
