services:
    audiobookshelf:
        image: advplyr/audiobookshelf:latest
        container_name: audiobookshelf
        ports:
            - 13378:80
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Chicago
        volumes:
            - ./audiobookshelf:/config
            - ./audiobookshelf/metadata:/metadata
            - /mnt/HDD1/books/audiobooks:/audiobooks
      restart: unless-stopped
