services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt:/srv
      - /home/chiefbash/docker/filebrowser/filebrowser.db:/filebrowser.db # "touch filebrowser.db" in /home/chiefbash/docker/filebrowser
      - /home/chiefbash/docker/filebrowser/settings.json:/settings.json # "touch settings.json" in /home/chiefbash/docker/filebrowser
    ports:
      - 8095:80
    restart: unless-stopped
  filezilla:
    image: jlesage/filezilla:latest
    container_name: filezilla
    ports:
      - 5050:5050
    volumes:
      - /home/chiefbash/docker/filezilla/config:/config:rw
      - /mnt:/storage:rw
    restart: unless-stopped
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/chiefbash/docker/freshrss/config:/config
    ports:
      - 8085:80
    restart: unless-stopped
  speedtest:
    image: openspeedtest/latest
    container_name: speedtest
    ports:
      - 3020:3000
      - 3021:3001
    restart: unless-stopped
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/chiefbash/docker/syncthing/config:/config
      - /home/chiefbash:/data1
      - /mnt:/data2
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped  
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command: --cleanup=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
