 services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=docker
      # - PLEX_CLAIM=claim-rhNiAn2ybhrGrt5K2B1M
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
    volumes:
      - /mnt/HDD0/plex:/config
      - /mnt/HDD0/plex/movies:/movies
      - /mnt/HDD0/plex/shows:/shows
      - /mnt/HDD0/plex/videos:/videos
      # - /mnt/HDD0/plex/halloween:/halloween
      #- /mnt/HDD0/plex/christmas:/christmas
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/chiefbash/docker/tautulli/config:/config
    ports:
      - 8181:8181
    restart: unless-stopped
