services:
  filebot:
    image: jlesage/filebot:latest
    container_name: filebot
    ports:
      - 5800:5800
    volumes:
      - ./filebot/:/config:rw
      - /mnt/HDD1/media:/storage:rw
    restart: unless-stopped

  handbrake:
    image: jlesage/handbrake:latest
    container_name: handbrake
    ports:
      - 5810:5810
    volumes:
      - ./handbrake:/config:rw
      - /mnt/HDD1:/storage:ro
      - /mnt/HDD1/handbrake/watch:/watch:rw
      - /mnt/HDD1/handbrake/complete:/output:rw
      - /mnt/HDD1/handbrake/trash:/trash:rw
    restart: unless-stopped

  makemkv:
    image: jlesage/makemkv:latest
    container_name: makemkv
    ports:
      - 5820:5820
    volumes:
      - ./makemkv/config:/config:rw
      - /mnt/HDD1:/storage:ro
      - /mnt/HDD1/makemkv:/output:rw
    devices:
      - /dev/sr0:/dev/sr0
      - /dev/sg2:/dev/sg2 #may need to do the following command after every update/restart: sudo modprobe sg
    restart: unless-stopped

  mkvtoolnix:
    image: jlesage/mkvtoolnix:latest
    container_name: mkvtoolnix
    ports:
      - 5830:5830
    volumes:
      - ./mkvtoolnix:/config:rw
      - /mnt/HDD1/makemkv:/storage:rw
    restart: unless-stopped
