services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/chiefbash/docker/kavita/config:/config
      - /mnt/HDD15/books/books:/books
      - /mnt/HDD15/books/comics:/comics
      - /mnt/HDD15/books/manga:/manga
    ports:
      - 5000:5000
    restart: unless-stopped
