services:
  makemkv:
    image: jlesage/makemkv:latest
    container_name: makemkv
    ports:
      - 5820:5820
    volumes:
      - /docker/makemkv/config:/config:rw
      - /mnt/HDD1:/storage:ro
      - /mnt/HDD1/makemkv/encode:/output:rw
    devices:
      - /dev/sr0:/dev/sr0
      - /dev/sg2:/dev/sg2 #may need to do the following command after every update/restart: sudo modprobe sg
    restart: unless-stopped
