services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    environment:
      - TZ=America/Chicago
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/chiefbash/docker/homarr/config:/config
      - /home/chiefbash/docker/homarr/data:/data
    ports:
      - 7575:7575
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/chiefbash/docker/bazarr/config:/config
      - /mnt/HDD0/plex/movies:/movies
      - /mnt/HDD0/plex/shows:/shows
    ports:
      - 6767:6767
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/chiefbash/docker/lidarr/config:/config
      - /mnt/HDD0/music:/music
      - /mnt/HDD16/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/chiefbash/docker/overseerr/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/chiefbash/docker/radarr/config:/config
      - /mnt/HDD0/plex/movies:/movies
      - /mnt/HDD16/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:0.4.19-nightly
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/chiefbash/docker/readarr/config:/config
      - /mnt/HDD0/books/:/books
      - /mnt/HDD16/downloads:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /home/chiefbash/docker/sonarr/config:/config
      - /mnt/HDD0/plex/shows:/shows
      - /mnt/HDD16/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
